# Generated by Django 3.1.1 on 2022-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0002_auto_20220528_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
